services:
  phntm_cloud_bridge:
    image: phntm/cloud-bridge:latest
    container_name: phntm-cloud-bridge
    hostname: phntm-cloud-bridge.local
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 1337:1337
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ~/cloud_bridge:/phntm_cloud_bridge
    command:
      #/bin/sh -c "while sleep 1000; do :; done"
      /bin/sh /phntm_cloud_bridge/run.bridge.sh

  phntm_bridge_ui:
    image: phntm/cloud-bridge:latest
    container_name: phntm-bridge-ui
    hostname: phntm-bridge-ui.local
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ~/cloud_bridge:/phntm_cloud_bridge
    command:
      #/bin/sh -c "while sleep 1000; do :; done"
      /bin/sh /phntm_cloud_bridge/run.web-ui.sh
